name: {{cookiecutter.project_slug}}

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/dockerfile/app/Dockerfile
    ports:
      - "{{cookiecutter.project_external_port}}:80"
    volumes:
      - ./src:/app/src
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80

  worker:
    build:
      context: .
      dockerfile: docker/dockerfile/app/Dockerfile
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A worker.celery worker --autoscale=100,3 --loglevel=info
    volumes:
      - ./src:/app/src
    environment:
      - TZ=Europe/Paris

  celery_beat:
    build:
      context: .
      dockerfile: docker/dockerfile/app/Dockerfile
    command: watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A worker.celery beat -S redbeat.RedBeatScheduler --loglevel=info
    volumes:
      - ./src:/app/src
    environment:
      - TZ=Europe/Paris
    depends_on:
      - broker

  broker:
    image: redis:7
    ports:
      - "6379:6379"