name: {{cookiecutter.project.slug}}

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/dockerfile/app/Dockerfile
    ports:
      - "{{cookiecutter.project_external.port}}:80"
    volumes:
      - ./src:/app/src
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80


