name: {{cookiecutter.project_slug}}-stage


services:

  app:
    container_name: {{cookiecutter.project_slug}}-stage-app
    image: {{cookiecutter.project_registry_url}}:${IMAGE_TAG:-latest}
    restart: always
    environment:
      - TZ=Europe/Paris
    expose:
      - '80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{cookiecutter.project_slug}}_stage.entrypoints=web,websecure"
      - "traefik.http.routers.{{cookiecutter.project_slug}}_stage.rule=Host(`staging.{{cookiecutter.project_domain_name}}`)"