name: {{cookiecutter.project.slug}}-prod


services:

  app:
    container_name: {{cookiecutter.project_slug}}-prod-app
    image: {{cookiecutter.project_registry_url}}:latest
    restart: always
    environment:
      - TZ=Europe/Paris
    expose:
      - '80'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{{cookiecutter.project_slug}}_prod.entrypoints=web,websecure"
      - "traefik.http.routers.{{cookiecutter.project_slug}}_prod.rule=Host(`{{cookiecutter.project_domain_name}}`)"
